-- ============================================================================
-- QUICK START: Sample Data for Reading Recording Feature
-- Copy and paste this into your Supabase SQL Editor
-- Replace the UUIDs with your actual IDs
-- ============================================================================

-- STEP 1: Insert a Reading Level
INSERT INTO public.reading_levels (level_number, title, description) 
VALUES (1, 'Beginner Level', 'Basic reading for young learners')
RETURNING id;  -- Copy this ID!

-- RESULT: You'll get a UUID like: 11111111-1111-1111-1111-111111111111
-- ⬇️ Replace 'LEVEL_ID_HERE' below with this ID


-- STEP 2: Insert a Task (Choose ONE based on your schema)

-- OPTION A: If using tasks table with reading_level_id
INSERT INTO public.tasks (title, description, reading_level_id, "order", unlocks_next_level) 
VALUES ('The Cat and The Bird', 'Story about friendship', 'LEVEL_ID_HERE', 1, false)
RETURNING id;

-- OPTION B: If using reading_tasks table with level_id  
INSERT INTO public.reading_tasks (level_id, title, description, "order") 
VALUES ('LEVEL_ID_HERE', 'The Cat and The Bird', 'Story about friendship', 1)
RETURNING id;

-- RESULT: You'll get a UUID like: 22222222-2222-2222-2222-222222222222
-- ⬇️ Replace 'TASK_ID_HERE' below with this ID


-- STEP 3: Add PDF Material
INSERT INTO public.task_materials (task_id, material_title, material_file_path, material_type) 
VALUES ('TASK_ID_HERE', 'Cat and Bird Story PDF', 'reading-materials/cat-bird.pdf', 'pdf');


-- STEP 4: Create Student Progress Record
-- First, get a student's user_id from auth.users:
-- SELECT s.user_id FROM students s LIMIT 1;
-- Then replace 'STUDENT_USER_ID_HERE' below

INSERT INTO public.student_task_progress (student_id, task_id, attempts_left, completed) 
VALUES ('STUDENT_USER_ID_HERE', 'TASK_ID_HERE', 3, false);


-- STEP 5: Sample Recording (after student uploads)
-- The actual recording_url will be generated by Supabase storage
INSERT INTO public.student_readings (student_id, task_id, recording_url, needs_grading) 
VALUES (
    'STUDENT_USER_ID_HERE', 
    'TASK_ID_HERE',
    'https://YOUR_PROJECT.supabase.co/storage/v1/object/public/student_voice/audio123.m4a',
    true
);


-- STEP 6: Teacher Grades the Recording
UPDATE public.student_readings 
SET score = 8.5, 
    teacher_comments = 'Good job! Keep practicing.',
    needs_grading = false,
    graded_at = NOW()
WHERE student_id = 'STUDENT_USER_ID_HERE' 
  AND task_id = 'TASK_ID_HERE';


-- ============================================================================
-- VERIFY DATA
-- ============================================================================
-- Run this to see all your data connected:

SELECT 
    rl.title as "Level",
    rt.title as "Task",
    tm.material_title as "PDF",
    sp.attempts_left as "Attempts Left",
    sr.score as "Grade",
    sr.teacher_comments as "Comments"
FROM reading_levels rl
LEFT JOIN reading_tasks rt ON rt.level_id = rl.id
LEFT JOIN task_materials tm ON tm.task_id = rt.id
LEFT JOIN student_task_progress sp ON sp.task_id = rt.id
LEFT JOIN student_readings sr ON sr.task_id = rt.id
WHERE rl.level_number = 1;

-- ============================================================================
-- COMPLETE EXAMPLE WITH REAL-LOOKING DATA
-- ============================================================================
-- Note: You must run these in order and use the RETURNING IDs!

/*
-- 1. Get a real student
SELECT s.user_id, s.student_name FROM students s LIMIT 1;

-- 2. Get a real teacher  
SELECT t.id, t.teacher_name FROM teachers t LIMIT 1;

-- 3. Get a real classroom
SELECT c.id, c.class_name FROM class_rooms c LIMIT 1;

-- 4. Insert level
DO $$
DECLARE
    v_level_id uuid;
    v_task_id uuid;
    v_student_id uuid;
BEGIN
    -- Create level
    INSERT INTO public.reading_levels (level_number, title, description) 
    VALUES (1, 'Level 1: Beginning Reader', 'Introduction to reading')
    RETURNING id INTO v_level_id;

    -- Create task
    INSERT INTO public.reading_tasks (level_id, title, description, "order") 
    VALUES (v_level_id, 'My First Story', 'A fun story about a cat and bird', 1)
    RETURNING id INTO v_task_id;

    -- Add material
    INSERT INTO public.task_materials (task_id, material_title, material_file_path, material_type) 
    VALUES (v_task_id, 'My First Story PDF', 'stories/first-story.pdf', 'pdf');

    -- Create progress for first student
    SELECT user_id INTO v_student_id FROM students LIMIT 1;
    
    IF v_student_id IS NOT NULL THEN
        INSERT INTO public.student_task_progress (student_id, task_id, attempts_left, completed) 
        VALUES (v_student_id, v_task_id, 3, false);
        
        RAISE NOTICE 'Sample data created! Level: %, Task: %, Student: %', 
            v_level_id, v_task_id, v_student_id;
    ELSE
        RAISE NOTICE 'No student found. Create a student first.';
    END IF;
END $$;
*/


